"""E2E: agent tool calling via pydantic-ai FunctionModel.

An actual pydantic-ai Agent with workspace tools bound via
``make_workspace_tools()`` executes deterministic tool calls through
FunctionModel — no LLM API key required.

Note: pydantic-ai propagates tool exceptions directly (only
``ModelRetry`` is caught for retry).  Workspace errors like
``WorkspaceFileNotFoundError`` surface as unhandled exceptions.
Production integration should wrap tools to convert workspace
errors into ``ModelRetry`` for graceful LLM-driven recovery.
"""

from __future__ import annotations

import inspect
import uuid

import pytest
from pydantic_ai import Agent
from pydantic_ai import ModelMessage
from pydantic_ai import ModelResponse
from pydantic_ai import TextPart
from pydantic_ai import ToolCallPart
from pydantic_ai.models.function import AgentInfo
from pydantic_ai.models.function import FunctionModel

from soliplex_workspace.exceptions import WorkspaceAlreadyExistsError
from soliplex_workspace.exceptions import WorkspaceFileNotFoundError
from soliplex_workspace.providers.mock import MockWorkspaceProvider
from soliplex_workspace.tools.bridge import make_workspace_tools

pytestmark = pytest.mark.e2e


def _room_id() -> str:
    return f"agent-{uuid.uuid4().hex[:8]}"


# -- Deterministic model functions ---------------------------------


def _workspace_agent_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Calls list -> read -> write, then returns text."""
    tool_returns = [
        p for m in messages for p in m.parts if p.part_kind == "tool-return"
    ]
    step = len(tool_returns)

    if step == 0:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_list",
                    {"path": "/", "recursive": True},
                )
            ]
        )
    if step == 1:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_read",
                    {"path": "/notes/readme.md"},
                )
            ]
        )
    if step == 2:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_write",
                    {
                        "path": "/summary.md",
                        "content": "# Summary\nGenerated by agent.",
                    },
                )
            ]
        )
    return ModelResponse(
        parts=[TextPart("I read the workspace and wrote a summary.")]
    )


def _read_nonexistent_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Tries to read a file that doesn't exist."""
    return ModelResponse(
        parts=[
            ToolCallPart(
                "workspace_read",
                {"path": "/nonexistent.txt"},
            )
        ]
    )


def _overwrite_direct_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Writes with overwrite=True directly."""
    tool_returns = [
        p for m in messages for p in m.parts if p.part_kind == "tool-return"
    ]
    if len(tool_returns) == 0:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_write",
                    {
                        "path": "/existing.txt",
                        "content": "new content",
                        "overwrite": True,
                    },
                )
            ]
        )
    return ModelResponse(parts=[TextPart("File overwritten successfully.")])


def _overwrite_blocked_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Tries to write without overwrite (should fail)."""
    return ModelResponse(
        parts=[
            ToolCallPart(
                "workspace_write",
                {
                    "path": "/existing.txt",
                    "content": "new content",
                },
            )
        ]
    )


def _empty_write_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Writes an empty file, then reads it back."""
    tool_returns = [
        p for m in messages for p in m.parts if p.part_kind == "tool-return"
    ]
    step = len(tool_returns)

    if step == 0:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_write",
                    {"path": "/empty.txt", "content": ""},
                )
            ]
        )
    if step == 1:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_read",
                    {"path": "/empty.txt"},
                )
            ]
        )
    return ModelResponse(parts=[TextPart("Empty file created and verified.")])


# -- Fixtures ------------------------------------------------------


@pytest.fixture
async def workspace_env():
    """Provider + room with seed files for agent tests."""
    provider = MockWorkspaceProvider()
    room_id = _room_id()
    await provider.create_workspace(room_id, "Agent Test Room")
    await provider.create_folder(room_id, "/notes")
    await provider.upload_file(
        room_id,
        "/notes/readme.md",
        b"# README\nThis is the project readme.",
    )
    return provider, room_id


# -- Tests ---------------------------------------------------------


class TestAgentCallsWorkspaceTools:
    """Agent drives list -> read -> write via FunctionModel."""

    async def test_three_tool_calls(self, workspace_env):
        provider, room_id = workspace_env
        tools = make_workspace_tools(provider, room_id)

        agent: Agent[None, str] = Agent(
            FunctionModel(_workspace_agent_model),
            tools=tools,
        )
        result = await agent.run("Summarize my workspace")

        # Agent made 3 tool calls then returned text
        assert "summary" in result.output.lower()

        # Verify /summary.md was created on the provider
        data = await provider.download_file(room_id, "/summary.md")
        assert b"# Summary" in data
        assert b"Generated by agent" in data


class TestAgentToolErrorPropagation:
    """Workspace errors propagate through pydantic-ai.

    pydantic-ai only catches ``ModelRetry`` for retry logic.
    All other exceptions (including ``WorkspaceError`` subclasses)
    propagate directly.  Production integration should wrap tools
    to convert workspace errors to ``ModelRetry``.
    """

    async def test_nonexistent_file_raises(self, workspace_env):
        provider, room_id = workspace_env
        tools = make_workspace_tools(provider, room_id)

        agent: Agent[None, str] = Agent(
            FunctionModel(_read_nonexistent_model),
            tools=tools,
        )
        with pytest.raises(WorkspaceFileNotFoundError):
            await agent.run("Read a missing file")

    async def test_overwrite_blocked_raises(self, workspace_env):
        provider, room_id = workspace_env
        await provider.upload_file(room_id, "/existing.txt", b"original")

        tools = make_workspace_tools(provider, room_id)
        agent: Agent[None, str] = Agent(
            FunctionModel(_overwrite_blocked_model),
            tools=tools,
        )
        with pytest.raises(WorkspaceAlreadyExistsError):
            await agent.run("Write to existing file")


class TestAgentToolSignaturesIntrospectable:
    """Bound tools have correct signatures for framework use."""

    async def test_signatures(self, workspace_env):
        provider, room_id = workspace_env
        tools = make_workspace_tools(provider, room_id)

        for tool in tools:
            assert tool.__doc__ is not None, (
                f"{tool.__name__} missing docstring"
            )
            sig = inspect.signature(tool)
            param_names = list(sig.parameters.keys())
            assert "provider" not in param_names, (
                f"{tool.__name__} leaks provider"
            )
            assert "room_id" not in param_names, (
                f"{tool.__name__} leaks room_id"
            )


class TestAgentOverwriteWithFlag:
    """overwrite=True works through agent tool calling."""

    async def test_overwrite_succeeds(self, workspace_env):
        provider, room_id = workspace_env
        await provider.upload_file(room_id, "/existing.txt", b"original")

        tools = make_workspace_tools(provider, room_id)
        agent: Agent[None, str] = Agent(
            FunctionModel(_overwrite_direct_model),
            tools=tools,
        )
        result = await agent.run("Overwrite existing file")
        assert "overwritten" in result.output.lower()

        data = await provider.download_file(room_id, "/existing.txt")
        assert data == b"new content"


class TestAgentEmptyContentWrite:
    """Agent can write and read back an empty file."""

    async def test_empty_file(self, workspace_env):
        provider, room_id = workspace_env
        tools = make_workspace_tools(provider, room_id)

        agent: Agent[None, str] = Agent(
            FunctionModel(_empty_write_model),
            tools=tools,
        )
        result = await agent.run("Create an empty file")
        assert "empty" in result.output.lower()

        data = await provider.download_file(room_id, "/empty.txt")
        assert data == b""


def _lazy_write_model(
    messages: list[ModelMessage],
    info: AgentInfo,  # noqa: ARG001
) -> ModelResponse:
    """Writes a file — workspace should be auto-created."""
    tool_returns = [
        p for m in messages for p in m.parts if p.part_kind == "tool-return"
    ]
    if len(tool_returns) == 0:
        return ModelResponse(
            parts=[
                ToolCallPart(
                    "workspace_write",
                    {"path": "/auto.txt", "content": "auto-created"},
                )
            ]
        )
    return ModelResponse(parts=[TextPart("Workspace was lazily created.")])


class TestAgentLazyWorkspaceCreation:
    """Agent workspace tools auto-create workspace on first call."""

    async def test_agent_lazy_workspace_creation(self):
        provider = MockWorkspaceProvider()
        room_id = _room_id()
        # No workspace pre-created
        tools = make_workspace_tools(provider, room_id)

        agent: Agent[None, str] = Agent(
            FunctionModel(_lazy_write_model),
            tools=tools,
        )
        result = await agent.run("Write to a new workspace")
        assert "lazily" in result.output.lower()

        # Workspace was auto-created
        ws = await provider.get_workspace(room_id)
        assert ws is not None

        # File was written
        data = await provider.download_file(room_id, "/auto.txt")
        assert data == b"auto-created"
